spring:
  application:
    name: ielts-speaking-app
  
  # Database Configuration - PostgreSQL
  datasource:
    url: jdbc:postgresql://localhost:5432/ielts_speaking_app
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME:ytms_user}
    password: ${DB_PASSWORD:yt}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  
  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          time_zone: UTC
        connection:
          characterEncoding: UTF-8
        jpa:
          hibernate:
            naming:
              physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  
  # File upload configuration
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

# Server Configuration
server:
  port: 8080
  servlet:
    context-path: /api

# Google Cloud Configuration
google:
  cloud:
    project-id: ${GOOGLE_CLOUD_PROJECT_ID:inspire26}
    speech:
      language-code: en-US
      model: latest_long
      enable-automatic-punctuation: true
      use-enhanced: true
    text-to-speech:
      voice-name: en-US-Standard-A
      language-code: en-US


# JWT Configuration
jwt:
  expiration: 86400000 # 24 hours in milliseconds

# Application Configuration
app:
  # Question Management Configuration
  use-deepseek-api: ${USE_DEEPSEEK_API:false}  # Set to true to occasionally use DeepSeek API for questions
  question-rotation-days: ${QUESTION_ROTATION_DAYS:50}  # Days to avoid repeating questions for a user

gcp:
  project-id: ${GCP_PROJECT_ID:inspire26}  # Google Cloud Project ID
